# Generated by Django 3.2.25 on 2025-05-07 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_time_minutes_recipe_time_munites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='time_munites',
            new_name='time_minutes',
        ),
    ]
